
env=qa
qa.url=https://qa.amazon1.com
dev.url=https://dev.amazon2.com
stage.url=https://stage.amazon3.com
prod.url=https://amazon4.com

baseUrl=https://www.amazon.in
browser=chrome
product=HP smart tank
model=Smart Tank 589
quantity=2